name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: "${{ matrix.os }}"
    strategy:
      matrix:
        include:
          # - os: macos-latest
          #   target: x86_64-apple-darwin
          #   suffix: ""
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            suffix: ""
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            suffix: .exe
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
      - uses: Swatinem/rust-cache@v2
      - run: sudo apt-get install -y ocl-icd-opencl-dev
        if: matrix.os == 'ubuntu-latest'
      - run: |
          vcpkg --triplet=x64-windows install opencl
          set LIB=C:\vcpkg\packages\opencl_x64-windows\lib
        if: matrix.os == 'windows-latest'
      - run: cargo build --release --target ${{ matrix.target }} -DNVIDIA_DEVICE -cl-fp32-correctly-rounded-divide-sqrt
        env:
          LIB: C:\vcpkg\packages\opencl_x64-windows\lib
      - uses: actions/upload-artifact@v4
        with:
          name: yggdrasil-vanity-${{ matrix.target }}
          path: target/${{ matrix.target }}/release/yggdrasil-vanity${{ matrix.suffix }}
